name: Kops install demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install kops
        run: |
          curl -Lo /tmp/kops https://github.com/kubernetes/kops/releases/download/$KOPS_VERSION/kops-linux-amd64
          ls -la /tmp
          chmod +x /tmp/kops
          sudo mv /tmp/kops /usr/local/bin/kops
        env:
          KOPS_VERSION: "v1.21.1"
      - name: Run kops
        run: |
          kops
      - run: echo "Done!"
